### ISSUE TITLE
small Bug

### ISSUE THREAD

**Issue by geisterdach** [realfabianw/cardmarket4j#3]
Hallo Fabian,

ich habe deinen Java-Wrapper gerade mal getestet. Gleich bei der ersten Anfrage war ein kleiner Bug drin. Als ich meine privaten Nachrichten abgerufen habe, ist mir aufgefallen dass Message-Id kein int sondern ein String sein muss. Nachdem ich das gefixt habe, hat es aber funktioniert. Cool! Weißt du ob in deinem Projekt noch mehrere Bugs drin sind, und hast fehlen noch Funktionen, bzw hast du noch vor daran weiter zu arbeiten (oder zu testen).

Du kannst mich auch gerne bei Email kontaktieren: wtwetewthzfth@yahoo.de

LG Daniel

**Comment by realfabianw** [comment]
Hey,
ich habe den Datentyp von messageId gerade geändert, danke für den Hinweis. Außerdem habe ich noch die Dependency Javatuples entfernt, da sie ohnehin nur an einer Stelle benutzt wurde. 
MfG
Fabian
